### ISSUE TITLE
Stack overflow (SOLVED)

### ISSUE THREAD

**Issue by bluimes** [mimblewimble/grin-wallet#486]
Hello, 

Recently I updated the node to 4.0 beta. I get this weird error when I try to listen with the wallet. Seems like something is ending up in a loop, but I am clueless. 

{deleted}@{deleted}-{deleted}:/mnt/ssd500/grin-wallet$ ./grin-wallet listen
Password:
20200719 11:22:59.731 WARN grin_wallet_controller::controller - Starting TOR Hidden Service for API listener at address {deleted}, binding to 0.0.0.0:3415
20200719 11:23:02.873 WARN grin_wallet_controller::controller - Starting HTTP Foreign listener API server at 0.0.0.0:3415.
20200719 11:23:02.873 WARN grin_wallet_controller::controller - HTTP Foreign listener started.
20200719 11:23:02.873 WARN grin_wallet_controller::controller - Slatepack Address is: {deleted}

thread 'tokio-runtime-worker' has overflowed its stack
fatal runtime error: stack overflow
Aborted (core dumped)

Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04

CPU: 2x Quad Core Intel Xeon E5405 (-MCP SMP-) speed: 2083 MHz
Kernel: 5.4.0-40-generic x86_64 Up: 1d 7h 13m Mem: 1104.5/3934.3 MiB (28.1%)

**Comment by bluimes** [comment]
Problem is solved after pulling new grin-wallet... reason remains unknown.

**Comment by marekyggdrasil** [comment]
Wallet output:

```sh
$ ./grin-wallet owner_api
20201206 04:58:09.877 INFO grin_util::logger - log4rs is initialized, file level: Trace, stdout level: Trace, min. level: Trace
20201206 04:58:09.878 INFO grin_wallet - Using wallet configuration file at /home/marek/.grin/main/grin-wallet.toml
20201206 04:58:09.878 INFO grin_wallet - This is Grin Wallet version 5.1.0-alpha.1 (git v4.0.0-30-g7896001), built for x86_64-unknown-linux-gnu by rustc 1.48.0 (7eac88abb 2020-11-16).
20201206 04:58:09.878 DEBUG grin_wallet - Built with profile "release", features "".
20201206 04:58:09.983 DEBUG grin_wallet_impls::lifecycle::seed - Seed file path: /home/marek/.grin/main/wallet_data/wallet.seed
Password: 
20201206 04:58:11.307 DEBUG grin_store::lmdb - DB Mapsize for /home/marek/.grin/main/wallet_data/db/lmdb is 134217728
20201206 04:58:11.307 TRACE grin_store::lmdb - DB map size: 134217728
20201206 04:58:11.307 TRACE grin_store::lmdb - Space used: 40960
20201206 04:58:11.307 TRACE grin_store::lmdb - Space remaining: 134176768
20201206 04:58:11.307 TRACE grin_store::lmdb - Percent used: 0.0003  Percent threshold: 0.9000
20201206 04:58:11.307 TRACE grin_store::lmdb - Resize threshold not met (percent-based)
20201206 04:58:11.309 DEBUG grin_wallet_impls::lifecycle::seed - Using wallet seed file at: /home/marek/.grin/main/wallet_data/wallet.seed
20201206 04:58:11.335 WARN grin_wallet_controller::controller - Starting HTTP Owner API server at 127.0.0.1:3420.
20201206 04:58:11.335 WARN grin_wallet_controller::controller - HTTP Owner listener started.

thread 'tokio-runtime-worker' has overflowed its stack
fatal runtime error: stack overflow
Aborted
```

( so I reproduced the problem )

My local repo is at:

```sh
$ git log -n 1 master
commit 78960015fc6c609386370171b10983adf0f22057 (HEAD -> master, origin/master, origin/HEAD)
Author: jaspervdm <j@sper.dev>
Date:   Tue Dec 1 14:48:07 2020 +0100

    Bump master version to 5.1.0-alpha.1 (#536)
    
    * Bump version to 5.0.0-beta.1
    
    * Bump version to 5.1.0-alpha.1
    
    * Switch to grin master
```

( so pulling from master does not fix the problem, it must have been caused by something else )
